workspace 'ZLAuthorizer'
xcodeproj 'AuthorizerExample/AuthorizerExample.xcodeproj'
platform :ios, '7.0'
pod 'Lockbox'
pod 'AFNetworking', '~> 2.0'
pod 'NSString+Validation'
pod 'BlocksKit', '~> 2.2.0'